import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import RippleCursor from "@/components/RippleCursor";
import HighlightProvider from "./contexts/highlight.provider";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased relative bg-dark-navy h-dvh overflow-hidden pt-25.5 pb-27.75 max-[1440px]:pt-20 max-[1440px]:pb-15`}
      >
        <RippleCursor />
        <HighlightProvider>{children}</HighlightProvider>
      </body>
    </html>
  );
}
