import type { Metadata } from "next";
import { Geist_Mono, Jersey_10, Mochiy_Pop_One } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SmoothScrollProvider from "@/components/SmoothScrollProvider";
import ScrollIndicator from "@/components/ScrollIndicator";
import { ThemeProvider } from "@/hooks/ThemeProvider";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jersey10 = Jersey_10({
  variable: "--font-jersey-10",
  subsets: ["latin"],
  weight: ["400"],
});

const mochiyPopOne = Mochiy_Pop_One({
  variable: "--font-mochiy-pop-one",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistMono.variable, jersey10.variable, mochiyPopOne.variable)}
      suppressHydrationWarning
    >
      <body className="bg-white">
        <SmoothScrollProvider />
        <ScrollIndicator />
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
