import type { Metadata } from "next";
import { Geist_Mono, TikTok_Sans, Jersey_10 } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SmoothScrollProvider from "@/components/custom-ui/SmoothScrollProvider";
import ScrollIndicator from "@/components/custom-ui/ScrollIndicator";

const tiktokSans = TikTok_Sans({
  variable: "--font-tiktok-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jersey10 = Jersey_10({
  variable: "--font-jersey-10",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistMono.variable, jersey10.variable, tiktokSans.variable)}
      suppressHydrationWarning
    >
      <body className="bg-black">
        <SmoothScrollProvider />
        <ScrollIndicator />
        {children}
      </body>
    </html>
  );
}
